### ISSUE TITLE
Question on how to proceed

### ISSUE THREAD

**Issue by selewis** [ncbi/citation-exporter#2]
Hi, 
This isn't really an issue, but it seemed the simplest way to contact you. Here's what I'm trying to do.
Given a list of starter PMIDs (~2500)
Find all the PMIDs that cite this starter set
For each of the citing PMIDs
1. Get the grant number for the citing publication
2. Get the total funding for that grant number

I also would like to get the grant number and total funding for the starting PMIDs. 
I'm trying to look at reuse, and (in dollar terms) return on the original outlay.

@selewis

p.s. the name citation-exported seemed like it would help with at least one step. I've cobbled together some Perl to pull things from NIH reporter dumpers I've downloaded (for funding)

**Comment by Klortho** [comment]
Hi,

No, I'm afraid that your question has nothing to do with the citation-exporter. You should get a quick response if you write to the PMC help desk: pubmedcentral@ncbi.nlm.nih.gov
